name: update-readme

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run the script
        run: bash scripts/generate_html.sh
      - name: Commit files
        run: |
          git config --local user.name "Tim Froidcoeur"
          git config --local user.email "tim.froidcoeur@gmail.com"
          git add *.html
          git commit -m "Updated html"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
